.TH TMPWATCH 8 "Mon May 05 2000"
.UC 4
.SH NAME
tmpwatch \- removes files which haven't been accessed for a period of time
.SH SYNOPSIS
\fBtmpwatch\fR [-u|-m|-c] [-faqstv] [--verbose] [--force] [--all] [--test] 
               [--fuser ] [--atime|--mtime|--ctime] [--quiet] <hours> <dirs>

.SH DESCRIPTION
\fBtmpwatch\fR recursively removes files which haven't been accessed
for a given number of hours. Normally, it's used to clean up directories
which are used for temporary holding space such as /tmp.

When changing directories, \fBtmpwatch\fR is very sensitive to possible
race conditions and will exit with an error if one is detected. It does
not follow symbolic links in the directories it's cleaning (even if a
symbolic link is given as its argument), will not switch filesystems,
 and only removes empty directories and regular files. 

By default, \fBtmpwatch\fR dates files by their atime (access time), not
their mtime (modification time). If files aren't being removed when
\fBls -l\fR implies they should be, use \fBls -u\fR to examine their
atime to see if that explains the problem.

The \fIhours\fR parameter defines the threshold for removing files. If
the file has not been accessed for \fIhours\fR hours, the file is removed.
Following this, one or more directories may be given for \fBtmpwatch\fR
to clean up.

.SH OPTIONS
.TP
\fB-u, -\-atime\fR
Make the decision about deleting a file based on the file's atime
(access time). This is the default. This option is incompatible with 
-\-mtime and -\-ctime.

.TP
\fB-m, -\-mtime\fR
Make the decision about deleting a file based on the file's mtime
(modification time) instead of the atime. This option is incompatible
with -\-atime and -\-ctime.

.TP
\fB-c, -\-ctime\fR
Make the decision about deleting a file based on the file's ctime
(inode change time) instead of the atime; for directories, make the
decision based on the mtime.  This option is incompatible with -\-atime
and -\-mtime.

.TP
\fB-a, -\-all\fR
Remove all file types, not just regular files and directories.

.TP
\fB-f, -\-force\fR
Remove files even if root doesn't have write access (akin to \fBrm -f\fR).

.TP
\fB-t, -\-test\fR
Doesn't remove files, but goes through the motions of removing them. This
implies \fB\-v\fR.

.TP
\fB-s, -\-fuser\fR
Attempt to use the "fuser" command to see if a file is already open
before removing it.  Not enabled by default.   Does help in some
circumstances, but not all.  Dependent on fuser being installed in
/sbin.

.TP
\fB-v, -\-verbose\fR
Print a verbose display. Two levels of verboseness are available -- use
this option twice to get the most verbose output.

.SH SEE ALSO
.IR cron (1),
.IR ls (1),
.IR rm (1),
.IR fuser (1)

.SH WARNINGS
GNU-style long options are not supported on HP-UX.

.SH AUTHORS
.nf
Erik Troan <ewt@redhat.com>
Preston Brown <pbrown@redhat.com>
.fi
